version: "3.8"

services:
  backend:
    build: .
    container_name: lexis-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
      - processed_volume:/app/processed
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis  # Добавляем Redis для Celery

  db:
    image: postgres:15
    container_name: lexis-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lexis_user
      POSTGRES_PASSWORD: lexis_pass
      POSTGRES_DB: lexis_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lexis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    container_name: lexis-celery-worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
      - processed_volume:/app/processed
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - backend

volumes:
  pgdata:
  redis_data:
  uploads_volume:
  processed_volume: